version: "3"

networks:
  backend:
  frontend:
  
services:
  
  nginx:
    container_name: my_nginx
    networks:
      - frontend
      - backend
    image: nginx:1.19
    ports:
      - "${HTTPS_PORT}:443"
      - "${HTTP_PORT}:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./web:/var/www/html
    